package com.note.cms.dao;

import com.note.cms.data.model.TbDoorLock;
import com.note.cms.data.model.TbDoorLockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbDoorLockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door_lock
     *
     * @mbg.generated Tue Aug 08 16:45:17 CST 2017
     */
    long countByExample(TbDoorLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door_lock
     *
     * @mbg.generated Tue Aug 08 16:45:17 CST 2017
     */
    int deleteByExample(TbDoorLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door_lock
     *
     * @mbg.generated Tue Aug 08 16:45:17 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door_lock
     *
     * @mbg.generated Tue Aug 08 16:45:17 CST 2017
     */
    int insert(TbDoorLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door_lock
     *
     * @mbg.generated Tue Aug 08 16:45:17 CST 2017
     */
    int insertSelective(TbDoorLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door_lock
     *
     * @mbg.generated Tue Aug 08 16:45:17 CST 2017
     */
    List<TbDoorLock> selectByExample(TbDoorLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door_lock
     *
     * @mbg.generated Tue Aug 08 16:45:17 CST 2017
     */
    TbDoorLock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door_lock
     *
     * @mbg.generated Tue Aug 08 16:45:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbDoorLock record, @Param("example") TbDoorLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door_lock
     *
     * @mbg.generated Tue Aug 08 16:45:17 CST 2017
     */
    int updateByExample(@Param("record") TbDoorLock record, @Param("example") TbDoorLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door_lock
     *
     * @mbg.generated Tue Aug 08 16:45:17 CST 2017
     */
    int updateByPrimaryKeySelective(TbDoorLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door_lock
     *
     * @mbg.generated Tue Aug 08 16:45:17 CST 2017
     */
    int updateByPrimaryKey(TbDoorLock record);
}