package com.note.cms.dao;

import com.note.cms.data.model.TbDoor;
import com.note.cms.data.model.TbDoorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbDoorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    long countByExample(TbDoorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int deleteByExample(TbDoorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int insert(TbDoor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int insertSelective(TbDoor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    List<TbDoor> selectByExample(TbDoorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    TbDoor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbDoor record, @Param("example") TbDoorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int updateByExample(@Param("record") TbDoor record, @Param("example") TbDoorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int updateByPrimaryKeySelective(TbDoor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int updateByPrimaryKey(TbDoor record);
}