package com.note.cms.dao;

import com.note.cms.data.model.TbGuest;
import com.note.cms.data.model.TbGuestExample;
import java.util.List;

import com.note.cms.data.vo.GuestClickInOutVo;
import com.note.cms.data.vo.GuestReportParams;
import org.apache.ibatis.annotations.Param;

public interface TbGuestMapper {
    List<GuestClickInOutVo> findClickInOutRecord(GuestReportParams params);

    List<GuestClickInOutVo> findClickInOutRecordByIpc(GuestReportParams params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    long countByExample(TbGuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    int deleteByExample(TbGuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    int insert(TbGuest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    int insertSelective(TbGuest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    List<TbGuest> selectByExample(TbGuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    TbGuest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbGuest record, @Param("example") TbGuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    int updateByExample(@Param("record") TbGuest record, @Param("example") TbGuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    int updateByPrimaryKeySelective(TbGuest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    int updateByPrimaryKey(TbGuest record);
}