package com.note.cms.dao;

import com.note.cms.data.model.TbGuestRole;
import com.note.cms.data.model.TbGuestRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbGuestRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_role
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    long countByExample(TbGuestRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_role
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    int deleteByExample(TbGuestRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_role
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_role
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    int insert(TbGuestRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_role
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    int insertSelective(TbGuestRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_role
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    List<TbGuestRole> selectByExample(TbGuestRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_role
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    TbGuestRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_role
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbGuestRole record, @Param("example") TbGuestRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_role
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    int updateByExample(@Param("record") TbGuestRole record, @Param("example") TbGuestRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_role
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    int updateByPrimaryKeySelective(TbGuestRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_role
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    int updateByPrimaryKey(TbGuestRole record);
}