package com.note.cms.dao;

import com.note.cms.data.model.TbGuestModifyRecord;
import com.note.cms.data.model.TbGuestModifyRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbGuestModifyRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_modify_record
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    long countByExample(TbGuestModifyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_modify_record
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    int deleteByExample(TbGuestModifyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_modify_record
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_modify_record
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    int insert(TbGuestModifyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_modify_record
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    int insertSelective(TbGuestModifyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_modify_record
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    List<TbGuestModifyRecord> selectByExample(TbGuestModifyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_modify_record
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    TbGuestModifyRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_modify_record
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbGuestModifyRecord record, @Param("example") TbGuestModifyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_modify_record
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    int updateByExample(@Param("record") TbGuestModifyRecord record, @Param("example") TbGuestModifyRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_modify_record
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    int updateByPrimaryKeySelective(TbGuestModifyRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_modify_record
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    int updateByPrimaryKey(TbGuestModifyRecord record);
}