package com.note.cms.dao;

import com.note.cms.data.model.TbInitSession;
import com.note.cms.data.model.TbInitSessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbInitSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_init_session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    long countByExample(TbInitSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_init_session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int deleteByExample(TbInitSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_init_session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_init_session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int insert(TbInitSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_init_session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int insertSelective(TbInitSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_init_session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    List<TbInitSession> selectByExample(TbInitSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_init_session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    TbInitSession selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_init_session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbInitSession record, @Param("example") TbInitSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_init_session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int updateByExample(@Param("record") TbInitSession record, @Param("example") TbInitSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_init_session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int updateByPrimaryKeySelective(TbInitSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_init_session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    int updateByPrimaryKey(TbInitSession record);
}