package com.note.cms.dao;

import com.note.cms.data.model.TbSnapshot;
import com.note.cms.data.model.TbSnapshotExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbSnapshotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_snapshot
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    long countByExample(TbSnapshotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_snapshot
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    int deleteByExample(TbSnapshotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_snapshot
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_snapshot
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    int insert(TbSnapshot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_snapshot
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    int insertSelective(TbSnapshot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_snapshot
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    List<TbSnapshot> selectByExample(TbSnapshotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_snapshot
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    TbSnapshot selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_snapshot
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbSnapshot record, @Param("example") TbSnapshotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_snapshot
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    int updateByExample(@Param("record") TbSnapshot record, @Param("example") TbSnapshotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_snapshot
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    int updateByPrimaryKeySelective(TbSnapshot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_snapshot
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    int updateByPrimaryKey(TbSnapshot record);
}