package com.note.cms.data.model;

import java.io.Serializable;
import java.util.Date;

public class TbDoor implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_door.id
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_door.name
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_door.address
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_door.create_time
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_door
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public TbDoor(Integer id, String name, String address, Date createTime) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_door
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public TbDoor() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_door.id
     *
     * @return the value of tb_door.id
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_door.id
     *
     * @param id the value for tb_door.id
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_door.name
     *
     * @return the value of tb_door.name
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_door.name
     *
     * @param name the value for tb_door.name
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_door.address
     *
     * @return the value of tb_door.address
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_door.address
     *
     * @param address the value for tb_door.address
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_door.create_time
     *
     * @return the value of tb_door.create_time
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_door.create_time
     *
     * @param createTime the value for tb_door.create_time
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}