package com.note.cms.data.model;

import java.io.Serializable;
import java.util.Date;

public class TbGuestRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest_role.id
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest_role.name
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest_role.security_level
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    private Integer securityLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest_role.auto_open_door
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    private Byte autoOpenDoor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest_role.create_time
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest_role.limit_time
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    private Boolean limitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest_role.open_time
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    private Integer openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guest_role
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_role
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public TbGuestRole(Integer id, String name, Integer securityLevel, Byte autoOpenDoor, Date createTime, Boolean limitTime, Integer openTime) {
        this.id = id;
        this.name = name;
        this.securityLevel = securityLevel;
        this.autoOpenDoor = autoOpenDoor;
        this.createTime = createTime;
        this.limitTime = limitTime;
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_role
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public TbGuestRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest_role.id
     *
     * @return the value of tb_guest_role.id
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest_role.id
     *
     * @param id the value for tb_guest_role.id
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest_role.name
     *
     * @return the value of tb_guest_role.name
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest_role.name
     *
     * @param name the value for tb_guest_role.name
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest_role.security_level
     *
     * @return the value of tb_guest_role.security_level
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public Integer getSecurityLevel() {
        return securityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest_role.security_level
     *
     * @param securityLevel the value for tb_guest_role.security_level
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public void setSecurityLevel(Integer securityLevel) {
        this.securityLevel = securityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest_role.auto_open_door
     *
     * @return the value of tb_guest_role.auto_open_door
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public Byte getAutoOpenDoor() {
        return autoOpenDoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest_role.auto_open_door
     *
     * @param autoOpenDoor the value for tb_guest_role.auto_open_door
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public void setAutoOpenDoor(Byte autoOpenDoor) {
        this.autoOpenDoor = autoOpenDoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest_role.create_time
     *
     * @return the value of tb_guest_role.create_time
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest_role.create_time
     *
     * @param createTime the value for tb_guest_role.create_time
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest_role.limit_time
     *
     * @return the value of tb_guest_role.limit_time
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public Boolean getLimitTime() {
        return limitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest_role.limit_time
     *
     * @param limitTime the value for tb_guest_role.limit_time
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public void setLimitTime(Boolean limitTime) {
        this.limitTime = limitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest_role.open_time
     *
     * @return the value of tb_guest_role.open_time
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public Integer getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest_role.open_time
     *
     * @param openTime the value for tb_guest_role.open_time
     *
     * @mbg.generated Sun Aug 20 18:13:30 CST 2017
     */
    public void setOpenTime(Integer openTime) {
        this.openTime = openTime;
    }
}