package com.note.cms.data.model;

import java.io.Serializable;
import java.util.Date;

public class TbGuestModifyRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest_modify_record.id
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest_modify_record.user_id
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest_modify_record.create_time
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest_modify_record.guest_id
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    private Integer guestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest_modify_record.operation
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    private String operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest_modify_record.guest_name
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    private String guestName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guest_modify_record
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_modify_record
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    public TbGuestModifyRecord(Integer id, Integer userId, Date createTime, Integer guestId, String operation, String guestName) {
        this.id = id;
        this.userId = userId;
        this.createTime = createTime;
        this.guestId = guestId;
        this.operation = operation;
        this.guestName = guestName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest_modify_record
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    public TbGuestModifyRecord() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest_modify_record.id
     *
     * @return the value of tb_guest_modify_record.id
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest_modify_record.id
     *
     * @param id the value for tb_guest_modify_record.id
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest_modify_record.user_id
     *
     * @return the value of tb_guest_modify_record.user_id
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest_modify_record.user_id
     *
     * @param userId the value for tb_guest_modify_record.user_id
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest_modify_record.create_time
     *
     * @return the value of tb_guest_modify_record.create_time
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest_modify_record.create_time
     *
     * @param createTime the value for tb_guest_modify_record.create_time
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest_modify_record.guest_id
     *
     * @return the value of tb_guest_modify_record.guest_id
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    public Integer getGuestId() {
        return guestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest_modify_record.guest_id
     *
     * @param guestId the value for tb_guest_modify_record.guest_id
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    public void setGuestId(Integer guestId) {
        this.guestId = guestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest_modify_record.operation
     *
     * @return the value of tb_guest_modify_record.operation
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest_modify_record.operation
     *
     * @param operation the value for tb_guest_modify_record.operation
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest_modify_record.guest_name
     *
     * @return the value of tb_guest_modify_record.guest_name
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    public String getGuestName() {
        return guestName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest_modify_record.guest_name
     *
     * @param guestName the value for tb_guest_modify_record.guest_name
     *
     * @mbg.generated Tue Oct 17 20:38:55 CST 2017
     */
    public void setGuestName(String guestName) {
        this.guestName = guestName == null ? null : guestName.trim();
    }
}