package com.note.cms.data.model;

import java.io.Serializable;
import java.util.Date;

public class TbGuest implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.id
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.image
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.code
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.guest_role_id
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private Integer guestRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.first_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private Date firstTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.last_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private Date lastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.create_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.name
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.card_no
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.access_guest_id
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private Integer accessGuestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.age
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.gender
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.room
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private String room;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.count
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.lock_start_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private Date lockStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.lock_end_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private Date lockEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.upload_image
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private String uploadImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.user_id_create
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private Integer userIdCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.last_modify_user_id
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private Integer lastModifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_guest.last_modify_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_guest
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public TbGuest(Integer id, String image, String code, Integer guestRoleId, Date firstTime, Date lastTime, Date createTime, String name, String cardNo, Integer accessGuestId, Integer age, Integer gender, String room, Integer count, Date lockStartTime, Date lockEndTime, String uploadImage, Integer userIdCreate, Integer lastModifyUserId, Date lastModifyTime) {
        this.id = id;
        this.image = image;
        this.code = code;
        this.guestRoleId = guestRoleId;
        this.firstTime = firstTime;
        this.lastTime = lastTime;
        this.createTime = createTime;
        this.name = name;
        this.cardNo = cardNo;
        this.accessGuestId = accessGuestId;
        this.age = age;
        this.gender = gender;
        this.room = room;
        this.count = count;
        this.lockStartTime = lockStartTime;
        this.lockEndTime = lockEndTime;
        this.uploadImage = uploadImage;
        this.userIdCreate = userIdCreate;
        this.lastModifyUserId = lastModifyUserId;
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_guest
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public TbGuest() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.id
     *
     * @return the value of tb_guest.id
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.id
     *
     * @param id the value for tb_guest.id
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.image
     *
     * @return the value of tb_guest.image
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.image
     *
     * @param image the value for tb_guest.image
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.code
     *
     * @return the value of tb_guest.code
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.code
     *
     * @param code the value for tb_guest.code
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.guest_role_id
     *
     * @return the value of tb_guest.guest_role_id
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public Integer getGuestRoleId() {
        return guestRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.guest_role_id
     *
     * @param guestRoleId the value for tb_guest.guest_role_id
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setGuestRoleId(Integer guestRoleId) {
        this.guestRoleId = guestRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.first_time
     *
     * @return the value of tb_guest.first_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public Date getFirstTime() {
        return firstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.first_time
     *
     * @param firstTime the value for tb_guest.first_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setFirstTime(Date firstTime) {
        this.firstTime = firstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.last_time
     *
     * @return the value of tb_guest.last_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.last_time
     *
     * @param lastTime the value for tb_guest.last_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.create_time
     *
     * @return the value of tb_guest.create_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.create_time
     *
     * @param createTime the value for tb_guest.create_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.name
     *
     * @return the value of tb_guest.name
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.name
     *
     * @param name the value for tb_guest.name
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.card_no
     *
     * @return the value of tb_guest.card_no
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.card_no
     *
     * @param cardNo the value for tb_guest.card_no
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.access_guest_id
     *
     * @return the value of tb_guest.access_guest_id
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public Integer getAccessGuestId() {
        return accessGuestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.access_guest_id
     *
     * @param accessGuestId the value for tb_guest.access_guest_id
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setAccessGuestId(Integer accessGuestId) {
        this.accessGuestId = accessGuestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.age
     *
     * @return the value of tb_guest.age
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.age
     *
     * @param age the value for tb_guest.age
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.gender
     *
     * @return the value of tb_guest.gender
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.gender
     *
     * @param gender the value for tb_guest.gender
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.room
     *
     * @return the value of tb_guest.room
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public String getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.room
     *
     * @param room the value for tb_guest.room
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setRoom(String room) {
        this.room = room == null ? null : room.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.count
     *
     * @return the value of tb_guest.count
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.count
     *
     * @param count the value for tb_guest.count
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.lock_start_time
     *
     * @return the value of tb_guest.lock_start_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public Date getLockStartTime() {
        return lockStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.lock_start_time
     *
     * @param lockStartTime the value for tb_guest.lock_start_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setLockStartTime(Date lockStartTime) {
        this.lockStartTime = lockStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.lock_end_time
     *
     * @return the value of tb_guest.lock_end_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public Date getLockEndTime() {
        return lockEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.lock_end_time
     *
     * @param lockEndTime the value for tb_guest.lock_end_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setLockEndTime(Date lockEndTime) {
        this.lockEndTime = lockEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.upload_image
     *
     * @return the value of tb_guest.upload_image
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public String getUploadImage() {
        return uploadImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.upload_image
     *
     * @param uploadImage the value for tb_guest.upload_image
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setUploadImage(String uploadImage) {
        this.uploadImage = uploadImage == null ? null : uploadImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.user_id_create
     *
     * @return the value of tb_guest.user_id_create
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public Integer getUserIdCreate() {
        return userIdCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.user_id_create
     *
     * @param userIdCreate the value for tb_guest.user_id_create
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setUserIdCreate(Integer userIdCreate) {
        this.userIdCreate = userIdCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.last_modify_user_id
     *
     * @return the value of tb_guest.last_modify_user_id
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public Integer getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.last_modify_user_id
     *
     * @param lastModifyUserId the value for tb_guest.last_modify_user_id
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setLastModifyUserId(Integer lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_guest.last_modify_time
     *
     * @return the value of tb_guest.last_modify_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_guest.last_modify_time
     *
     * @param lastModifyTime the value for tb_guest.last_modify_time
     *
     * @mbg.generated Thu Sep 28 11:06:06 CST 2017
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}