package com.note.cms.data.model;

import java.io.Serializable;
import java.util.Date;

public class TbInitSession implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_init_session.id
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_init_session.session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    private String session;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_init_session.user_id
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_init_session.is_available
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    private Boolean isAvailable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_init_session.platform
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    private String platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_init_session.platform_version
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    private String platformVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_init_session.version
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_init_session.create_time
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_init_session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_init_session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public TbInitSession(Integer id, String session, Integer userId, Boolean isAvailable, String platform, String platformVersion, Integer version, Date createTime) {
        this.id = id;
        this.session = session;
        this.userId = userId;
        this.isAvailable = isAvailable;
        this.platform = platform;
        this.platformVersion = platformVersion;
        this.version = version;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_init_session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public TbInitSession() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_init_session.id
     *
     * @return the value of tb_init_session.id
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_init_session.id
     *
     * @param id the value for tb_init_session.id
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_init_session.session
     *
     * @return the value of tb_init_session.session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public String getSession() {
        return session;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_init_session.session
     *
     * @param session the value for tb_init_session.session
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public void setSession(String session) {
        this.session = session == null ? null : session.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_init_session.user_id
     *
     * @return the value of tb_init_session.user_id
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_init_session.user_id
     *
     * @param userId the value for tb_init_session.user_id
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_init_session.is_available
     *
     * @return the value of tb_init_session.is_available
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public Boolean getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_init_session.is_available
     *
     * @param isAvailable the value for tb_init_session.is_available
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public void setIsAvailable(Boolean isAvailable) {
        this.isAvailable = isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_init_session.platform
     *
     * @return the value of tb_init_session.platform
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_init_session.platform
     *
     * @param platform the value for tb_init_session.platform
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_init_session.platform_version
     *
     * @return the value of tb_init_session.platform_version
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public String getPlatformVersion() {
        return platformVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_init_session.platform_version
     *
     * @param platformVersion the value for tb_init_session.platform_version
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public void setPlatformVersion(String platformVersion) {
        this.platformVersion = platformVersion == null ? null : platformVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_init_session.version
     *
     * @return the value of tb_init_session.version
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_init_session.version
     *
     * @param version the value for tb_init_session.version
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_init_session.create_time
     *
     * @return the value of tb_init_session.create_time
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_init_session.create_time
     *
     * @param createTime the value for tb_init_session.create_time
     *
     * @mbg.generated Tue Jul 11 18:04:22 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}