package com.note.cms.data.model;

import java.io.Serializable;
import java.util.Date;

public class TbIpc implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ipc.id
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ipc.name
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ipc.address
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ipc.door_id
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    private Integer doorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ipc.create_time
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ipc.camera_id
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    private String cameraId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ipc.snap_timestamp
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    private String snapTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_ipc
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ipc
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public TbIpc(Integer id, String name, String address, Integer doorId, Date createTime, String cameraId, String snapTimestamp) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.doorId = doorId;
        this.createTime = createTime;
        this.cameraId = cameraId;
        this.snapTimestamp = snapTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ipc
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public TbIpc() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ipc.id
     *
     * @return the value of tb_ipc.id
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ipc.id
     *
     * @param id the value for tb_ipc.id
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ipc.name
     *
     * @return the value of tb_ipc.name
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ipc.name
     *
     * @param name the value for tb_ipc.name
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ipc.address
     *
     * @return the value of tb_ipc.address
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ipc.address
     *
     * @param address the value for tb_ipc.address
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ipc.door_id
     *
     * @return the value of tb_ipc.door_id
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public Integer getDoorId() {
        return doorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ipc.door_id
     *
     * @param doorId the value for tb_ipc.door_id
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public void setDoorId(Integer doorId) {
        this.doorId = doorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ipc.create_time
     *
     * @return the value of tb_ipc.create_time
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ipc.create_time
     *
     * @param createTime the value for tb_ipc.create_time
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ipc.camera_id
     *
     * @return the value of tb_ipc.camera_id
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public String getCameraId() {
        return cameraId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ipc.camera_id
     *
     * @param cameraId the value for tb_ipc.camera_id
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public void setCameraId(String cameraId) {
        this.cameraId = cameraId == null ? null : cameraId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ipc.snap_timestamp
     *
     * @return the value of tb_ipc.snap_timestamp
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public String getSnapTimestamp() {
        return snapTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ipc.snap_timestamp
     *
     * @param snapTimestamp the value for tb_ipc.snap_timestamp
     *
     * @mbg.generated Sat Jul 15 16:01:11 CST 2017
     */
    public void setSnapTimestamp(String snapTimestamp) {
        this.snapTimestamp = snapTimestamp == null ? null : snapTimestamp.trim();
    }
}