package com.note.cms.data.model;

import java.io.Serializable;
import java.util.Date;

public class TbSnapshot implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot.id
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot.imagefile
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    private String imagefile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot.create_time
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot.ipc_id
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    private Integer ipcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot.guest_code
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    private String guestCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_snapshot
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_snapshot
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    public TbSnapshot(Integer id, String imagefile, Date createTime, Integer ipcId, String guestCode) {
        this.id = id;
        this.imagefile = imagefile;
        this.createTime = createTime;
        this.ipcId = ipcId;
        this.guestCode = guestCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_snapshot
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    public TbSnapshot() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot.id
     *
     * @return the value of tb_snapshot.id
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot.id
     *
     * @param id the value for tb_snapshot.id
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot.imagefile
     *
     * @return the value of tb_snapshot.imagefile
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    public String getImagefile() {
        return imagefile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot.imagefile
     *
     * @param imagefile the value for tb_snapshot.imagefile
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    public void setImagefile(String imagefile) {
        this.imagefile = imagefile == null ? null : imagefile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot.create_time
     *
     * @return the value of tb_snapshot.create_time
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot.create_time
     *
     * @param createTime the value for tb_snapshot.create_time
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot.ipc_id
     *
     * @return the value of tb_snapshot.ipc_id
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    public Integer getIpcId() {
        return ipcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot.ipc_id
     *
     * @param ipcId the value for tb_snapshot.ipc_id
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    public void setIpcId(Integer ipcId) {
        this.ipcId = ipcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot.guest_code
     *
     * @return the value of tb_snapshot.guest_code
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    public String getGuestCode() {
        return guestCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot.guest_code
     *
     * @param guestCode the value for tb_snapshot.guest_code
     *
     * @mbg.generated Tue Jul 25 08:46:28 CST 2017
     */
    public void setGuestCode(String guestCode) {
        this.guestCode = guestCode == null ? null : guestCode.trim();
    }
}