package com.note.cms.data.model;

import java.io.Serializable;
import java.util.Date;

public class TbSnapshotFace implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.id
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.snapshot_id
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private Integer snapshotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.guest_code
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private String guestCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.ipc_id
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private Integer ipcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.galleries
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private String galleries;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.meta
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private String meta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.photo
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.timestamp
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.x1
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private Integer x1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.x2
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private Integer x2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.y1
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private Integer y1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.y2
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private Integer y2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.normalized
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private String normalized;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.age
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.thumbnail
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private String thumbnail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.photo_hash
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private String photoHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.person_id
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private Integer personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.face_id
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private Long faceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.gender
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_snapshot_face.confidence
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private Float confidence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_snapshot_face
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_snapshot_face
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public TbSnapshotFace(Integer id, Integer snapshotId, String guestCode, Integer ipcId, String galleries, String meta, String photo, Date timestamp, Integer x1, Integer x2, Integer y1, Integer y2, String normalized, Integer age, String thumbnail, String photoHash, Integer personId, Long faceId, String gender, Float confidence) {
        this.id = id;
        this.snapshotId = snapshotId;
        this.guestCode = guestCode;
        this.ipcId = ipcId;
        this.galleries = galleries;
        this.meta = meta;
        this.photo = photo;
        this.timestamp = timestamp;
        this.x1 = x1;
        this.x2 = x2;
        this.y1 = y1;
        this.y2 = y2;
        this.normalized = normalized;
        this.age = age;
        this.thumbnail = thumbnail;
        this.photoHash = photoHash;
        this.personId = personId;
        this.faceId = faceId;
        this.gender = gender;
        this.confidence = confidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_snapshot_face
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public TbSnapshotFace() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.id
     *
     * @return the value of tb_snapshot_face.id
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.id
     *
     * @param id the value for tb_snapshot_face.id
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.snapshot_id
     *
     * @return the value of tb_snapshot_face.snapshot_id
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public Integer getSnapshotId() {
        return snapshotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.snapshot_id
     *
     * @param snapshotId the value for tb_snapshot_face.snapshot_id
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setSnapshotId(Integer snapshotId) {
        this.snapshotId = snapshotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.guest_code
     *
     * @return the value of tb_snapshot_face.guest_code
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public String getGuestCode() {
        return guestCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.guest_code
     *
     * @param guestCode the value for tb_snapshot_face.guest_code
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setGuestCode(String guestCode) {
        this.guestCode = guestCode == null ? null : guestCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.ipc_id
     *
     * @return the value of tb_snapshot_face.ipc_id
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public Integer getIpcId() {
        return ipcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.ipc_id
     *
     * @param ipcId the value for tb_snapshot_face.ipc_id
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setIpcId(Integer ipcId) {
        this.ipcId = ipcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.galleries
     *
     * @return the value of tb_snapshot_face.galleries
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public String getGalleries() {
        return galleries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.galleries
     *
     * @param galleries the value for tb_snapshot_face.galleries
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setGalleries(String galleries) {
        this.galleries = galleries == null ? null : galleries.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.meta
     *
     * @return the value of tb_snapshot_face.meta
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public String getMeta() {
        return meta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.meta
     *
     * @param meta the value for tb_snapshot_face.meta
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setMeta(String meta) {
        this.meta = meta == null ? null : meta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.photo
     *
     * @return the value of tb_snapshot_face.photo
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.photo
     *
     * @param photo the value for tb_snapshot_face.photo
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.timestamp
     *
     * @return the value of tb_snapshot_face.timestamp
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.timestamp
     *
     * @param timestamp the value for tb_snapshot_face.timestamp
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.x1
     *
     * @return the value of tb_snapshot_face.x1
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public Integer getX1() {
        return x1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.x1
     *
     * @param x1 the value for tb_snapshot_face.x1
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setX1(Integer x1) {
        this.x1 = x1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.x2
     *
     * @return the value of tb_snapshot_face.x2
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public Integer getX2() {
        return x2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.x2
     *
     * @param x2 the value for tb_snapshot_face.x2
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setX2(Integer x2) {
        this.x2 = x2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.y1
     *
     * @return the value of tb_snapshot_face.y1
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public Integer getY1() {
        return y1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.y1
     *
     * @param y1 the value for tb_snapshot_face.y1
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setY1(Integer y1) {
        this.y1 = y1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.y2
     *
     * @return the value of tb_snapshot_face.y2
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public Integer getY2() {
        return y2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.y2
     *
     * @param y2 the value for tb_snapshot_face.y2
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setY2(Integer y2) {
        this.y2 = y2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.normalized
     *
     * @return the value of tb_snapshot_face.normalized
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public String getNormalized() {
        return normalized;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.normalized
     *
     * @param normalized the value for tb_snapshot_face.normalized
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setNormalized(String normalized) {
        this.normalized = normalized == null ? null : normalized.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.age
     *
     * @return the value of tb_snapshot_face.age
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.age
     *
     * @param age the value for tb_snapshot_face.age
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.thumbnail
     *
     * @return the value of tb_snapshot_face.thumbnail
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.thumbnail
     *
     * @param thumbnail the value for tb_snapshot_face.thumbnail
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail == null ? null : thumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.photo_hash
     *
     * @return the value of tb_snapshot_face.photo_hash
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public String getPhotoHash() {
        return photoHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.photo_hash
     *
     * @param photoHash the value for tb_snapshot_face.photo_hash
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setPhotoHash(String photoHash) {
        this.photoHash = photoHash == null ? null : photoHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.person_id
     *
     * @return the value of tb_snapshot_face.person_id
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.person_id
     *
     * @param personId the value for tb_snapshot_face.person_id
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.face_id
     *
     * @return the value of tb_snapshot_face.face_id
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public Long getFaceId() {
        return faceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.face_id
     *
     * @param faceId the value for tb_snapshot_face.face_id
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setFaceId(Long faceId) {
        this.faceId = faceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.gender
     *
     * @return the value of tb_snapshot_face.gender
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.gender
     *
     * @param gender the value for tb_snapshot_face.gender
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_snapshot_face.confidence
     *
     * @return the value of tb_snapshot_face.confidence
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public Float getConfidence() {
        return confidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_snapshot_face.confidence
     *
     * @param confidence the value for tb_snapshot_face.confidence
     *
     * @mbg.generated Wed Oct 11 15:05:32 CST 2017
     */
    public void setConfidence(Float confidence) {
        this.confidence = confidence;
    }
}